apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: observability
  labels:
    app: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
        - name: load-generator
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -- checkout login cart inventory
              routes="$@"
              i=0
              while true; do
                i=$((i+1))
                ridx=$((RANDOM % 4 + 1))
                route=$(echo $routes | cut -d' ' -f$ridx)
                wget -q -O /dev/null "http://sample-app.observability.svc.cluster.local:8000/$route"
                sleep 0.5
              done
