apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-generator
  namespace: observability
  labels:
    app: trace-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-generator
  template:
    metadata:
      labels:
        app: trace-generator
    spec:
      containers:
        - name: telemetrygen
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - traces
            - --otlp-endpoint=otel-collector.observability.svc.cluster.local:4317
            - --otlp-insecure
            - --duration=inf
            - --rate=2
            - --child-spans=3
            - --service=sample-app
